ADD_SCENE(fn_test, start, Start)
ADD_SCENE(fn_test, fn_info, FNInfo)
ADD_SCENE(fn_test, life_info, LifeInfo)
ADD_SCENE(fn_test, wiring, Wiring)
ADD_SCENE(fn_test, about, About)
ADD_SCENE(fn_test, detect, Detect)
ADD_SCENE(fn_test, test, Test)
ADD_SCENE(fn_test, timeout, Timeout)
